### ISSUE TITLE
Question about required calls

### ISSUE THREAD

**Issue by mcrimi** [solgenomics/BrAPI-Pedigree-Viewer#1]
Hi @dauglyon ,

This is a very promising BrAPP! I'm very keen in replacing in replacing the BMS current pedigree viewer with this. 

One question: I see in your demo gif that you're traversing the tree in both directions, so it seems to me like the code must be relying on the [Pedigree call ](https://github.com/plantbreeding/API/blob/master/Specification/Germplasm/GermplasmPedigree.md) to get parents and the yet to be brapified [Progeny call](https://github.com/plantbreeding/API/issues/151) to get the progenies. Am I right?

If that's the case I'll can forward with implementing the Pedigree call in BMS as it is defined now and wait for the progeny spec to to be Merged.

Once again, thanks so much for sharing this high quality tools with the community!

**Comment by dauglyon** [comment]
Yes, this is correct. And thank you!
